name: simple_e_commerce
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  bot_toast: ^4.1.3
  flutter_svg: ^2.1.0
  flutter_spinkit: ^5.2.1
  animate_do: ^4.2.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  dropdown_button2:
  image_picker:
  mime:
  cached_network_image:
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  awesome_notifications: ^0.10.1
  permission_handler: ^12.0.0+1
  awesome_bottom_bar: ^1.2.4
  equatable:
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
